import pandas as pd
import numpy as np

train = pd.read_csv('competitions/s6e8/data/train.csv')
test = pd.read_csv('competitions/s6e8/data/test.csv')

print('=== Train Shape ===')
print(train.shape)
print()
print('=== Test Shape ===')
print(test.shape)
print()
print('=== Train Columns ===')
print(train.columns.tolist())
print()
print('=== Train Dtypes ===')
print(train.dtypes)
print()
print('=== Missing Values (Train) ===')
print(train.isnull().sum())
print()
print('=== Target Distribution ===')
print(train['addicted_label'].value_counts(normalize=True))
print()
print('=== Train Head ===')
print(train.head())
print()
print('=== Train Describe ===')
print(train.describe())
